name: Release Telegram Bot

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build artifact
        run: zip -r bot.zip bot.py constants.py methods.py requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bot
          path: bot.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: bot
          path: ./

      - name: Create Release
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseName = 'Release from PR #' + context.payload.pull_request.number;
            const releaseBody = 'Release built from Pull Request #' + context.payload.pull_request.number;
            const fs = require('fs');
            const path = require('path');

            const file = fs.readFileSync(path.join(__dirname, 'bot.zip'));

            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'pr-' + context.payload.pull_request.number,
              name: releaseName,
              body: releaseBody,
              draft: false,
              prerelease: true
            }).then(({data}) => {
              console.log('Created release: ' + data.html_url);
              github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: data.id,
                name: 'bot.zip',
                data: file, // Тут передаем содержимое файла
                contentType: 'application/zip'
              }).then(({ data }) => {
                console.log('Uploaded asset: ' + data.browser_download_url);
              }).catch(error => {
                console.error('Error uploading asset:', error);
              });
            }).catch(error => {
              console.error('Error creating release:', error);
            });

