name: Test Telegram Bot Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile bot.py --name VoiceToTextBot

      - name: Package release files
        run: |
          mkdir release
          copy dist\\VoiceToTextBot.exe release\\VoiceToTextBot.exe
          copy .env.example release\\.env.example
          powershell Compress-Archive -Path release\\* -DestinationPath VoiceToTextBot.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pr-test
          name: Release from PR test
          body: |
            Автоматический релиз из pull request TEST.
            В архиве находятся:
            - VoiceToTextBot.exe
            - пример .env.example 
          files: |
            VoiceToTextBot.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
