name: Test Telegram Bot Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create run script (Bash)
        run: |
          echo '#!/bin/bash' > run.sh
          echo 'unzip bot.zip' >> run.sh
          echo 'python bot.py' >> run.sh
          chmod +x run.sh

      - name: Build artifact
        run: zip -r bot.zip bot.py constants.py methods.py requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot
          path: bot.zip


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: bot
          path: ./

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: test-release-manual
          release_name: Test Release
          body: Test release from manual run
          draft: false
          prerelease: true

      - name: Upload Release Asset - bot.zip
        uses: actions/upload-artifact@v3
        with:
          name: bot.zip
          path: ./bot.zip
          upload_url: ${{ steps.create_release.outputs.upload_url }}

      - name: Upload Release Asset - run.sh
        uses: actions/upload-artifact@v3
        with:
          name: run.sh
          path: ./run.sh
          upload_url: ${{ steps.create_release.outputs.upload_url }}

